#!/bin/bash


if [ "$1" == "3g" ]
then

sh /home/root/gprs_tower_3g > /home/root/tower_file

else

sh /home/root/gprs_tower > /home/root/tower_file

fi

tower_status=`cat /home/root/tower_file | grep +CSQ | awk '{print $2}'`

tower=`echo ${tower_status:0:2}`


if [ $tower -lt 10 ]
then

echo "1" > /home/root/tower_value

elif [ $tower -lt 15 ]
then                
           
echo "2" > /home/root/tower_value
                       
elif [ $tower -lt 20 ]
then                
           
echo "3" > /home/root/tower_value
                       
elif [ $tower -lt 25 ] 
then                
           
echo "4" > /home/root/tower_value
                       
elif [ $tower -lt 30 ] 
then                
           
echo "5" > /home/root/tower_value
                       
fi


