obj-m += printer.o

all:    
	make -C /home/elinux1/projects/Gokul_Backup/Yocto_nuvoton/7520_3.5_Inch/Kernel/linux-3.10.y-master/ M=$(PWD) modules
clean:    
	make -C /home/elinux1/projects/Gokul_Backup/Yocto_nuvoton/7520_3.5_Inch/Kernel/linux-3.10.y-master/ M=$(PWD) clean


