obj-m += printer.o

all:    
#	make -C /home/elinux1/projects/Gokul_Backup/Yocto_nuvoton/7510_2.8_Inch/Kernel/linux-3.10.y-master/ M=$(PWD) modules
	make -C /home/elinux1/projects/Gokul_Backup/Yocto_nuvoton/7510_2.8_Inch/LatestUpdate/NUC970_Linux_Kernel-master M=$(PWD) modules
clean:    
#	make -C /home/elinux1/projects/Gokul_Backup/Yocto_nuvoton/7510_2.8_Inch/Kernel/linux-3.10.y-master/ M=$(PWD) clean
	make -C /home/elinux1/projects/Gokul_Backup/Yocto_nuvoton/7510_2.8_Inch/LatestUpdate/NUC970_Linux_Kernel-master M=$(PWD) clean


