obj-m += printer.o

all:    
	make -C /home/elinux1/projects/Gokul_Backup/Yocto_nuvoton/7510_2.8_Inch/Kernel/linux-3.10.y-master/ M=$(PWD) modules
clean:    
	make -C /home/elinux1/projects/Gokul_Backup/Yocto_nuvoton/7510_2.8_Inch/Kernel/linux-3.10.y-master/ M=$(PWD) clean


